### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by srobayo222** [stevenvachon/handlebars-react#2]
Hey steven
Can you tell me how to use it?? i dont understand very well.... but i already install it with npm

**Comment by stevenvachon** [comment]
This is not finished, hence there is no release. I'm not sure if or when I'll return to it because I'm uncertain of the direction of frontend technology. For example: https://github.com/htmlx-org/HTMLx

**Comment by alex-jestin-taylor** [comment]
If that's the case can you update your README to say as much? I spent much of today trying to get it to work only to find this comment. Hope you finish it one day.
